sudo: false

language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

cache: apt

env:
    global:
        - SYMFONY_ENV=test

# Handle git submodules yourself
# https://stackoverflow.com/questions/15674064
git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

before_script:
  - echo 'date.timezone = America/Vancouver' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo | pecl install imagick
  - composer install -n -o

script:
  - ./vendor/bin/phpunit
